tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: wip-176-177
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
